sonar.organization=elrorro334
sonar.projectKey=elrorro334_cine-front
sonar.projectName=cine-front
sonar.sources=src
sonar.exclusions=node_modules/**, dist/**, **/*.spec.ts, **/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
